### ISSUE TITLE
nested if-else

### ISSUE THREAD

**Issue by ssunniezz** [pongchai/vendingmachine#1]
https://github.com/pongchai/vendingmachine/blob/a39be7868e8c19ee155c1864d3ca9549b1fe4133/app.py#L129-L145

you can replace nested if-else by:

if not vm:
                 return jsonify({"error": "Vending machine not found"}), 404

if not item:
                return jsonify({"error": "Item not found"}), 404

if item.quantity - quantity < 0:
                return jsonify({"error": "Not enough items in stock"}), 400
else:
                item.quantity = item.quantity - quantity
                db.session.commit()
                return jsonify({"message": "Item removed from stock"}), 200

**Comment by pongchai** [comment]
Thank for this :))

**Comment by pongchai** [comment]
Fixed
