### ISSUE TITLE
Everything in one file

### ISSUE THREAD

**Issue by SuphawitWongfu** [pongchai/vendingmachine#4]
https://github.com/pongchai/vendingmachine/blob/a39be7868e8c19ee155c1864d3ca9549b1fe4133/app.py#L1-L174
Putting every functions in one file is not a good idea when it comes to managing a project. By separating group of functions to different files, it is easier to fix when something goes wrong and add more structure to the project.  For example, each file can contain all CRUD operations for each table and you can have another file for running to project

**Comment by pongchai** [comment]
Fixed
